export const RECEIVED_ROOMS = 'RECEIVED_ROOMS';
export const ROOM_MODIFIED = 'ROOM_MODIFIED';
export const CREATE_ROOM = 'CREATE_ROOM';
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';
export const SET_SEARCH_ROOM_PATTERN = 'SET_SEARCH_ROOM_PATTERN';
export const SET_SEARCH_ROOM_USERS_PATTERN = 'SET_SEARCH_ROOM_USERS_PATTERN';

export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const MESSAGE_MODIFIED = 'MESSAGE_MODIFIED';
export const RECEIVED_MESSAGES = 'RECEIVED_MESSAGES';

export const RECEIVED_USER = 'RECEIVED_USER';
export const RECEIVED_USERS = 'RECEIVED_USERS';
export const USER_MODIFIED = 'USER_MODIFIED';
export const SET_USERNAME = 'SET_USERNAME';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';

export const FIREBASE_INIT = 'FIREBASE_INIT';

export const UNDO = 'UNDO';
